[package]
name="calculator"
version="0.1.0"
edition="2021"

[package.metadata]
appid="dev.wayan.calc"
appname="Appy Calculator"

[lib]
path="src/main.rs"
crate-type=["cdylib"]

[dependencies]
appy={path="../..",features=["glutin"]}
